# Generated by Django 5.1.6 on 2025-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='attended',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='attended',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
