# Generated by Django 5.1.6 on 2025-03-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('dessert', 'Dessert'), ('yogurt', 'Yogurt'), ('fruit_salad', 'Fruit Salad'), ('iced_coffee', 'Iced Coffee'), ('hot_drinks', 'Hot Drinks'), ('herbs', 'Herbs'), ('soda_cocktail', 'Soda Cocktail'), ('milkshake', 'Milkshake'), ('coffee', 'Coffee'), ('espresso', 'Espresso'), ('fruit_cocktail', 'Fruit Cocktail'), ('smoothie', 'Smoothie'), ('waffle', 'Waffle'), ('juices', 'Juices'), ('tea', 'Tea'), ('iced_tea', 'Iced Tea')], default='dessert', max_length=20),
        ),
    ]
